version: '3.10'
 
services:
 
  postgres:

    image: postgres:14.0

    environment:

      - POSTGRES_USER=airflow

      - POSTGRES_PASSWORD=airflow

      - POSTGRES_DB=airflow

    logging:

      options:

        max-size: 10m

        max-file: "3"

    networks:

      - ISS_proj
 
  webserver:

    image: apache/airflow:2.6.0-python3.10

    command: webserver

    entrypoint: ['/opt/airflow/script/entrypoint.sh']

    depends_on:

      - postgres

    environment:

      - LOAD_EX=n

      - EXECUTOR=Sequential

      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow

      - AIRFLOW_WEBSERVER_SECRET_KEY=this_is_a_very_secured_key

    logging:

      options:

        max-size: 10m

        max-file: "3"

    volumes:

      - ./dags:/opt/airflow/dags

      - ./script/entrypoint.sh:/opt/airflow/script/entrypoint.sh

      - ./requirements.txt:/opt/airflow/requirements.txt

    ports:

      - "8081:8080"  # Changez le port ici si nécessaire

    healthcheck:

      test: ['CMD-SHELL', "[ -f /opt/airflow/airflow-webserver.pid ]"]

      interval: 30s

      timeout: 30s

      retries: 3

    networks:

      - ISS_proj
 
  scheduler:

    image: apache/airflow:2.6.0-python3.10

    volumes:

      - ./dags:/opt/airflow/dags

      - ./script/entrypoint.sh:/opt/airflow/script/entrypoint.sh

      - ./requirements.txt:/opt/airflow/requirements.txt

    environment:

      - LOAD_EX=n

      - EXECUTOR=Sequential

      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow

      - AIRFLOW_WEBSERVER_SECRET_KEY=this_is_a_very_secured_key      

    command: bash -c "pip install -r ./requirements.txt && airflow db upgrade && airflow scheduler"

    networks:

      - ISS_proj
 
networks:

  ISS_proj:

    external: true
 